version: '3.7'
services:
  parslydb:
    image: mongo:latest
    environment:
      MONGO_INITDB_DATABASE: parslydb
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

volumes:
  mongodb_data_container:
